# Generated by Django 4.0.5 on 2022-08-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkup', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='post_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=30)),
                ('jobtittle', models.CharField(max_length=50)),
                ('wtype', models.CharField(choices=[('remote', 'remote'), ('hybrid', 'hybrid')], max_length=30)),
                ('jtype', models.CharField(choices=[('parttime', 'parttime'), ('fulltime', 'fulltime')], max_length=30)),
                ('experience', models.CharField(choices=[('<1', '<1'), ('1-2', '1-2'), ('2-3', '2-3'), ('3-4', '3-4'), ('4-5', '4-5'), ('5-6', '5-6'), ('6-7', '6-7'), ('7-8', '7-8'), ('8-9', '8-9'), ('9<', '9<')], max_length=30)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
