# Generated by Django 4.0.5 on 2022-08-04 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkup', '0003_post_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_job',
            old_name='jobtittle',
            new_name='jobtitle',
        ),
    ]
