# Generated by Django 4.0.5 on 2022-08-04 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkup', '0004_rename_jobtittle_post_job_jobtitle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post_job',
            new_name='postjobmodel',
        ),
    ]
