# Generated by Django 4.0.5 on 2022-08-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkup', '0005_rename_post_job_postjobmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjobmodel',
            name='experience',
            field=models.CharField(choices=[('0-1', '0-1'), ('1-2', '1-2'), ('2-3', '2-3'), ('3-4', '3-4'), ('4-5', '4-5'), ('5-6', '5-6'), ('6-7', '6-7'), ('7-8', '7-8'), ('8-9', '8-9'), ('9+ years', '9+ years')], max_length=30),
        ),
    ]
