# Generated by Django 4.0.5 on 2022-08-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkup', '0007_remove_user_email_remove_user_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='apply_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('country_code', models.IntegerField(choices=[('+91', '+91'), ('+99', '+99'), ('+90', '+90'), ('+66', '+66')])),
                ('resume', models.FileField(upload_to='myapp/static')),
                ('current_position', models.CharField(default='', max_length=100)),
                ('current_company', models.CharField(default='', max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('identification_number', models.CharField(max_length=50)),
                ('job_title', models.CharField(default='', max_length=50)),
                ('company_name', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
