# Generated by Django 4.0.5 on 2022-08-09 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkup', '0008_apply_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply_job',
            name='identification_number',
        ),
    ]
