# Generated by Django 4.0.5 on 2022-08-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkup', '0009_remove_apply_job_identification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_job',
            name='resume',
            field=models.FileField(default='', upload_to='linkup/static'),
        ),
    ]
